# Generated by Django 2.2.7 on 2019-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFeel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaryfield',
            name='speech_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
