# Generated by Django 2.2.7 on 2019-11-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IFeel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaryfield',
            name='parent_field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_fields', to='IFeel.QuestionaryField'),
        ),
    ]
