# Generated by Django 2.2.7 on 2019-11-16 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IFeel', '0002_auto_20191116_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='questionaries', to='IFeel.QuestionaryField'),
        ),
        migrations.AlterField(
            model_name='questionaryfield',
            name='parent_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_fields', to='IFeel.QuestionaryField'),
        ),
    ]
